export const VERSION='1.1.2';
export const BALANCE=Object.freeze({schema:1,maxLevel:100,offlineHours:12,step:.25,titanChance:1/250,elementChance:1/100,titanMultiplier:1.10,raidKeyChance:1/6500,moralePerSecond:1/450,lowMoralePenalty:.45,captureCooldown:3,maxLog:160,saveSeconds:15,qualityMultipliers:[.8,1,1.15,1.35,1.65,2],caps:[10,20,30,40,50,60,70,80,90,100,100]});
export const STYLES=['Melee','Ranged','Magic'];
export const ELEMENTS={Fire:{color:'#ff9669',effect:'Burns for 3% Attack each second for 6s.'},Ice:{color:'#96d9ff',effect:'Slows Speed by 20% for 5s.'},Lightning:{color:'#f1dc81',effect:'Every fifth attack chains to a second foe.'},Poison:{color:'#b2de81',effect:'Poisons for 2% max HP each second for 4s (capped at 30% Attack).'}};
export const QUALITIES=['Poor','Common','Fine','Superior','Epic','Legendary'];
export const SKILLS={logging:{name:'Woodcutting',icon:'♧',type:'gather',description:'Timber for snares, tools, and Feral care.'},mining:{name:'Mining',icon:'⛏',type:'gather',description:'Ore for equipment, lenses, and hunting catalysts.'},fishing:{name:'Fishing',icon:'≈',type:'gather',description:'Fish for battle meals and companion treats.'},foraging:{name:'Foraging',icon:'❧',type:'gather',description:'Herbs for medicine, fiber, and powerful lures.'},smithing:{name:'Smithing',icon:'⚒',type:'craft',description:'Four equipment slots. Six qualities. Salvage unwanted gear.'},weaving:{name:'Artifice',icon:'⌘',type:'craft',description:'Craft snares, appraisal lenses, and limited capture automation.'},cooking:{name:'Cooking',icon:'♨',type:'craft',description:'Make food for combat and treats for Morale.'},alchemy:{name:'Alchemy',icon:'⚗',type:'craft',description:'Brew revival medicine and expensive encounter catalysts.'}};
const regionRows=[
['Mosswood Reach','The green frontier','Warden Alder','Verdant Badge','#6caa87','Bramblekit Pebbleback Reedfin Thistlepip Mossbun Acornox Glimmermoth Rootfang Briarhart Thornwarden','Willow Copper Brooktrout Sweetleaf'],
['Copperfall Hills','Iron beneath the red earth','Prospector Rhea','Copper Badge','#c49874','Flintusk Craglet Copperwing Dusthare Shaleback Cindermite Oreclaw Russetmaw Bellhorn Ferralith','Cedar Tin Hillperch Bitterroot'],
['Tideglass Coast','Where the sea leaves silver','Captain Maren','Tidal Badge','#70b8c4','Foamkit Shellsnap Gullance Brinecoil Tidepup Pearlwing Coralfang Mistfin Breakerhorn Abyssail','Driftwood Iron Silverfin Seakelp'],
['Amberfen','A light through the mire','Keeper Oren','Amber Badge','#a4ad6b','Boglet Mireback Rushbeak Sporehop Fenmoth Siltjaw Venomane Lanternnewt Hollowhart Marshcrown','Alder Cobalt Mudpike Bogmint'],
['Emberstep Caldera','Life beneath the ash','Forgewalker Sera','Ember Badge','#d48c6c','Ashkit Coalback Sparkbeak Scorchhop Magmite Sootcoil Torchmaine Pyrewing Obsidrake Cinderking','Charwood Pyrite Embercarp Ashbloom'],
['Frostveil','The long blue silence','Watcher Ivar','Frost Badge','#a0c7df','Rimekit Snowback Hailwing Frosthare Icicleaf Tundrusk Glaciermaw Auroray Crystelhart Wintermaw','Frostpine Mithril Icechar Snowbell'],
['Stormspire','Above the thunderline','Skycaller Nyra','Tempest Badge','#b1aadf','Voltkit Stormback Kitebeak Thundhop Arcscarab Cloudcoil Tempestfang Fulgarwing Skyhorn Thundrake','Stormash Voltite Cloudkoi Stormsage'],
['Moonhollow','The forest remembers','Dreamkeeper Esme','Lunar Badge','#b8a1d5','Dusklynx Moonback Veilwing Whisperhare Dreammoth Gloomcoil Shadefang Silversong Lunahart Noctyra','Moonwood Silver Duskeel Moonwort'],
['Sunken Reliquary','An empire still breathing','Sentinel Cael','Relic Badge','#d4bb7a','Glyphkit Vaultback Brasswing Relichop Gearscarab Runecoil Aegismaw Prismwing Sentryhorn Auricore','Petrifiedwood Orichalcum Vaultbass Goldmoss'],
['Crown of the Wild','Where all paths converge','Firstkeeper Sol','Sovereign Badge','#dfc795','Dawnkit Worldback Starbeak Bloomhare Crownshell Astracoil Sovereignmane Empyrewing Everhart Primordrake','Worldroot Astralite Dawnsturgeon Lifebloom']];
export const AREAS=regionRows.map((r,i)=>({id:i,name:r[0],subtitle:r[1],champion:r[2],badge:r[3],color:r[4],names:r[5].split(' '),materials:r[6].split(' '),level:i*10+1,requirement:Math.min(90,i*10),kills:30+i*25,donation:30+i*15,crafts:8+i*4}));
export const ABILITIES={pounce:{name:'Pounce',text:'Strike the weakest enemy for 170% damage.',cooldown:13},taunt:{name:'Stand Fast',text:'Taunt all enemies and reduce incoming damage 35% for 5s.',cooldown:17},mend:{name:'Lifewater',text:'Heal the most injured ally for 180% Attack.',cooldown:15},volley:{name:'Barrage',text:'Hit every enemy for 75% damage.',cooldown:14},haste:{name:'Quickening',text:'Gain 35% Speed for 7s.',cooldown:17},rupture:{name:'Sunder',text:'Deal 130% damage and reduce Defense 25% for 7s.',cooldown:15},drain:{name:'Soul Sip',text:'Deal 140% damage and heal for half the damage.',cooldown:16},execute:{name:'Ambush',text:'Deal 220% damage to targets below 35% HP, otherwise 140%.',cooldown:15},ward:{name:'Groveward',text:'Heal all allies for 80% Attack and shield them for 5s.',cooldown:19},quake:{name:'Earthbreak',text:'Deal 110% damage to every foe and slow them for 5s.',cooldown:20}};
export const PASSIVES={keen:{name:'Keen Eye',text:'+8% critical chance.'},shell:{name:'Living Shell',text:'Takes 10% less damage.'},flow:{name:'Gentle Current',text:'Healing is 20% stronger.'},pierce:{name:'Needlepoint',text:'Ignores 15% of Defense.'},evasive:{name:'Lightfoot',text:'8% chance to evade incoming attacks.'},sturdy:{name:'Rooted',text:'Generates 60% more threat.'},leech:{name:'Night Nectar',text:'Basic attacks heal for 8% damage.'},hunt:{name:'Hunting Instinct',text:'Deals 12% more damage to injured targets.'},comfort:{name:'Quiet Presence',text:'Loses Morale 25% more slowly.'},resolve:{name:'Last Stand',text:'Takes 20% less damage below 35% HP.'}};
const profiles=[['Melee',[56,13,6,27],'pounce','keen','Quickfang'],['Melee',[78,8,13,12],'taunt','shell','Shell Bash'],['Magic',[48,13,7,22],'mend','flow','Waterbolt'],['Ranged',[46,15,5,31],'volley','pierce','Quillshot'],['Ranged',[49,11,6,36],'haste','evasive','Dash Strike'],['Melee',[67,12,11,17],'rupture','sturdy','Rending Bite'],['Magic',[48,16,7,25],'drain','leech','Lumen Bolt'],['Melee',[61,18,7,26],'execute','hunt','Fangrush'],['Magic',[73,14,12,21],'ward','comfort','Spirit Lance'],['Melee',[91,19,15,18],'quake','resolve','Crown Breaker']];
export const SPECIES=AREAS.flatMap(a=>a.names.map((name,j)=>{const p=profiles[(j+a.id%3)%10];return {id:a.id*10+j,name,area:a.id,style:p[0],base:p[1].map(x=>Math.round(x*1.05**a.id)),ability:p[2],passive:p[3],attack:p[4],rarity:j<4?'Common':j<7?'Uncommon':j<9?'Rare':'Apex',weight:[220,205,190,180,85,65,40,9,5,1][j],difficulty:[.8,.8,.85,.85,.95,1,1.05,1.22,1.3,1.65][j],drop:`essence${a.id}`,special:j%4,description:`${name} uses ${ABILITIES[p[2]].name.toLowerCase()} and ${PASSIVES[p[3]].name.toLowerCase()} to shape a fight.`};}));
// Apex identities: four Melee, three Ranged, three Magic. Existing IVs/base stats are untouched.
const apexStyles={19:['Ranged','volley','sturdy','Shale Cannon'],29:['Magic','drain','leech','Abyss Bolt'],39:['Magic','ward','comfort','Mire Hex'],69:['Ranged','volley','keen','Storm Quills'],79:['Magic','drain','leech','Nightfall'],89:['Ranged','rupture','pierce','Prism Salvo']};
for(const [id,[style,ability,passive,attack]] of Object.entries(apexStyles))Object.assign(SPECIES[id],{style,ability,passive,attack,description:`${SPECIES[id].name} uses ${ABILITIES[ability].name.toLowerCase()} and ${PASSIVES[passive].name.toLowerCase()} to shape a fight.`});
export const ITEMS={};
export const RECIPES=[];
const add=(id,name,type,extra={})=>ITEMS[id]={id,name,type,value:1,...extra};
add('fiber','Wild fiber','material',{value:2});add('scrap','Tempered salvage','material',{value:3});add('dust','Prismatic dust','material',{value:8});add('fragment','Ancient key fragment','material',{value:0});
for(const a of AREAS){
 const t=a.id,req=t*10+1;
 ['log','ore','fish','herb'].forEach((kind,j)=>add(`${kind}${t}`,a.materials[j]+({log:' timber',ore:' ore',fish:'',herb:''}[kind]),'material',{value:2+t*3,tier:t}));
 add(`essence${t}`,['Wild resin','Crag grit','Pearl shard','Fen spore','Ember scale','Rime crystal','Storm mote','Dream silk','Relic cog','Crown seed'][t],'material',{value:5+t*5,tier:t});
 const recipe=(id,skill,cost,seconds,xp,gold=0)=>RECIPES.push({id,skill,cost,seconds,xp,gold,level:req,tier:t});
 add(`snare${t}`,['Willow','Copperjaw','Tideweave','Ambercoil','Embersteel','Frostbound','Stormwoven','Moonseal','Reliclock','Sovereign'][t]+' snare','snare',{strength:1+t*.17,value:12+t*10,tier:t});
 recipe(`snare${t}`,'weaving',{[`log${t}`]:2,[`ore${t}`]:1,fiber:2,...(t?{log0:1}:{})},6+t,18+t*14);
 add(`food${t}`,['Brook roast','Hill stew','Silverfin platter','Fen chowder','Ember grill','Frost broth','Cloudkoi skewers','Dusk hotpot','Vault feast','Dawn banquet'][t],'food',{heal:35+t*45,value:8+t*12,tier:t});
 recipe(`food${t}`,'cooking',{[`fish${t}`]:2,log0:1},5+t,16+t*13);
 add(`treat${t}`,['Sweetleaf bites','Cedar chews','Sea-salt treats','Bogmint cakes','Ashbloom biscuits','Snowbell bonbons','Stormsage crisps','Moonwort truffles','Golden honeycakes','Lifebloom delights'][t],'treat',{morale:25+t*5,value:10+t*10,tier:t});
 recipe(`treat${t}`,'cooking',{[`herb${t}`]:2,[`fish${t}`]:1,fiber:1},8+t,22+t*14);
 add(`revive${t}`,['Wakeleaf balm','Bitterroot salve','Tidal restorative','Fenheart tonic','Emberheart elixir','Winterwake balm','Stormpulse draught','Dreamwake elixir','Relic renewal','Lifebloom panacea'][t],'revive',{heal:.3+t*.07,value:20+t*20,tier:t});
 recipe(`revive${t}`,'alchemy',{[`herb${t}`]:3,[`essence${t}`]:1,...(t?{herb0:2}:{})},10+t,28+t*18);
 const gearNames=[['Briar','Trail'],['Copper','Crag'],['Tideglass','Mariner'],['Amber','Mire'],['Embersteel','Pyre'],['Rime','Winter'],['Volt','Tempest'],['Moon','Dream'],['Relic','Sentinel'],['Astral','Sovereign']][t];
 ['head','armor','weapon','accessory'].forEach((slot,j)=>{const id=`${slot}${t}`;const stats=[{hp:8+t*5,def:1+t},{hp:14+t*8,def:2+t*1.4},{atk:3+t*2},{speed:2+t*.9}][j];add(id,`${gearNames[j%2]} ${['crest','mantle','fang','charm'][j]}`,'equipment',{slot,stats,tier:t,level:req,value:40+t*35,property:['threat','guard','crit','care'][j],propertyText:['+20% threat','5% damage reduction','+4% critical chance','15% less Morale loss'][j]});recipe(id,'smithing',{[`ore${t}`]:5,[`log${t}`]:2,[`essence${t}`]:1,...(t?{ore0:2,scrap:2}:{})},15+t*2,45+t*25,t*8);});
}
add('lens','Appraisal lens','appraise',{value:25});RECIPES.push({id:'lens',skill:'weaving',cost:{ore0:3,herb0:2,essence0:1},seconds:12,xp:35,gold:0,level:3,tier:0});
for(const [i,element] of Object.keys(ELEMENTS).entries()){const id='lure'+element;add(id,element+' resonance incense','lure',{element,value:600});RECIPES.push({id,skill:'alchemy',level:61,tier:6,cost:{herb0:30,herb6:20,[`essence${i+3}`]:15,dust:10},gold:1500,seconds:90,xp:650});}
add('lureTitan','Titanblood beacon','lure',{element:'Titan',value:2500});RECIPES.push({id:'lureTitan',skill:'alchemy',level:85,tier:8,cost:{herb0:100,ore0:100,herb8:40,essence8:30,dust:35},gold:10000,seconds:180,xp:1800});
add('autoseal','Warden seal','automation',{value:400});RECIPES.push({id:'autoseal',skill:'weaving',level:65,tier:6,cost:{log0:20,ore6:10,essence6:8,dust:5},gold:500,seconds:45,xp:450});
export const RAIDS=[{id:0,name:'The Root Below',boss:'Heartroot Colossus',key:'rootkey',species:9,badge:8,stages:['Sever the feeders','Break the thorn guard','Silence the heart'],reward:'heartrelic',property:'regen',text:'Heal 1% maximum HP on each basic attack.'},{id:1,name:'Eye of the Tempest',boss:'The Unending Storm',key:'stormkey',species:69,badge:9,stages:['Ground the conductors','Scatter the stormwings','Still the eye'],reward:'stormrelic',property:'chain',text:'Every fourth attack strikes another target for 65% damage.'},{id:2,name:'The First Wild',boss:'The First Sovereign',key:'crownkey',species:99,badge:10,stages:['Defeat the oathbound','Shatter the crown','Face the First Wild'],reward:'crownrelic',property:'wardheal',text:'Healing abilities grant allies 5 seconds of damage reduction.'}];
for(const r of RAIDS){add(r.key,`${r.name} key`,'key',{value:0});add(r.reward,['Heartroot pendant','Stormglass fang','Firstkeeper diadem'][r.id],'equipment',{slot:['accessory','weapon','head'][r.id],tier:9,level:90,value:12000,stats:[{hp:90,def:12},{atk:35,speed:5},{hp:75,def:15}][r.id],property:r.property,propertyText:r.text});RECIPES.push({id:r.key,skill:'weaving',level:75+r.id*10,tier:8,cost:{fragment:100,[`essence${7+r.id}`]:30},gold:5000,seconds:120,xp:1000});}
export const skillXP=level=>Math.floor(80*(1.12**(level-1)-1)/.12);
export const feralXP=level=>Math.floor(45*(1.105**(level-1)-1)/.105);
export function levelFor(xp,feral=false){const fn=feral?feralXP:skillXP;let l=1;while(l<100&&xp>=fn(l+1))l++;return l;}
export const ivMultiplier=iv=>.5+(iv-1)/99;
export const attackInterval=speed=>Math.max(1,10/(1+9*(Math.max(1,speed)-1)/49));
export const qualityWeights=level=>{const x=(level-1)/99;return [Math.max(1,28-27*x),45-20*x,20+5*x,6+20*x,.95+17*x,.05+4.95*x];};
