import {BALANCE as B,AREAS,SPECIES,ITEMS,RECIPES,ABILITIES,SKILLS,RAIDS,levelFor,ivMultiplier,attackInterval,qualityWeights} from './data.mjs';
export const clone=x=>JSON.parse(JSON.stringify(x));
export function rng(s){let x=s.rng|0;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0;return s.rng/4294967296;}
export const choose=(s,rows,weight=x=>x.weight)=>{let n=rng(s)*rows.reduce((v,x)=>v+weight(x),0);return rows.find(x=>(n-=weight(x))<0)||rows.at(-1);};
export const cap=s=>B.caps[s.badges.length];
export const lv=(s,id)=>levelFor(s.skills[id]||0);
export const feralLevel=(s,f)=>Math.min(cap(s),levelFor(f.xp,true));
export const quantity=(s,id)=>s.bag[id]||0;
export function add(s,id,n=1){if(!ITEMS[id]||!Number.isSafeInteger(n))throw Error('Invalid inventory change');const v=quantity(s,id)+n;if(v<0||v>1e12)throw Error('Invalid inventory amount');if(v)s.bag[id]=v;else delete s.bag[id];}
export function log(s,text,rare=false){s.log.unshift({time:s.clock,text,rare});s.log.length=Math.min(B.maxLog,s.log.length);}
export const ownedTeam=s=>s.team.map(id=>s.ferals.find(f=>f.id===id)).filter(Boolean);
export function createFeral(s,species,level=1,wild=true){const sp=SPECIES[species];const boosted=s.boost?.until>s.clock;const titan=wild&&rng(s)<B.titanChance*(boosted&&s.boost.element==='Titan'?3:1);let element=null;if(wild&&rng(s)<B.elementChance*(boosted&&s.boost.element!=='Titan'?4:1)){element=boosted&&s.boost.element!=='Titan'?s.boost.element:['Fire','Ice','Lightning','Poison'][Math.floor(rng(s)*4)];}const f={id:`f${++s.serial}`,species,iv:Array.from({length:4},()=>1+Math.floor(rng(s)*100)),titan,element,appraised:false,xp:0,level,enemy:wild,morale:100,bond:0,hp:1,timer:0,cooldown:2,status:{},gear:{},hits:0,threat:0};f.hp=stats(s,f).hp;return f;}
export function stats(s,f){const sp=SPECIES[f.species],l=f.enemy?f.level:feralLevel(s,f);const out={};['hp','atk','def','speed'].forEach((k,i)=>out[k]=sp.base[i]*ivMultiplier(f.iv[i])*(f.titan?B.titanMultiplier:1)*(k==='speed'?1:1+(l-1)*.055));for(const id of Object.values(f.gear||{})){const g=s.gear.find(g=>g.id===id);if(g)for(const [k,v] of Object.entries(ITEMS[g.item].stats))out[k]+=v*B.qualityMultipliers[g.quality];}if(f.bossScale){out.hp*=f.bossScale;out.atk*=f.bossAttack||1;out.def*=1.15;}
 const morale=f.enemy?1:1-B.lowMoralePenalty*(1-f.morale/100);out.atk*=morale;out.def*=morale;out.speed*=morale;if(f.status?.slow>0)out.speed*=.8;if(f.status?.haste>0)out.speed*=1.35;if(f.status?.sunder>0)out.def*=.75;out.hp=Math.max(1,Math.round(out.hp));out.atk=Math.max(1,out.atk);out.def=Math.max(0,out.def);out.speed=Math.max(1,out.speed);out.interval=attackInterval(out.speed);return out;}
export function newGame(seed=Date.now()){return {schema:B.schema,version:'1.0.0',rng:(seed>>>0)||1,serial:0,clock:Date.now(),lastWall:Date.now(),name:'Wanderer',started:false,gold:100,bag:{},gear:[],ferals:[],team:[],skills:Object.fromEntries(Object.keys(SKILLS).map(k=>[k,0])),badges:[],area:0,trainer:'combat',activity:null,combat:null,wildEncounters:{},log:[],seen:{},caught:{},kills:Array(10).fill(0),crafted:Array(10).fill(0),donated:{},claimed:{},research:[],raidWins:[0,0,0],storage:30,autoEat:true,food:'food0',snare:'snare0',hold:false,autoCapture:false,autoRarity:'Rare',boost:null,captureTimer:0,commandTimer:0,settings:{motion:true,sound:false},totals:{kills:0,captures:0,crafts:0,gathered:0},session:0};}
export function startGame(s,species,name){if(s.started)return;const f=createFeral(s,species,1,false);f.iv=[60,60,60,60];f.hp=stats(s,f).hp;s.ferals.push(f);s.team=[f.id];s.name=(name||'Wanderer').trim().slice(0,24)||'Wanderer';s.started=true;for(const [id,n]of Object.entries({snare0:8,food0:12,revive0:3,treat0:3}))add(s,id,n);log(s,`${SPECIES[species].name} joins your journey. Welcome to Mosswood Reach.`);}
export function tasks(s,a){return [{name:`Win ${a.kills} battles in ${a.name}`,done:s.kills[a.id]>=a.kills,current:Math.min(s.kills[a.id],a.kills),goal:a.kills},a.id%2===0?{name:`Craft ${a.crafts} items from this region's recipes`,done:s.crafted[a.id]>=a.crafts,current:Math.min(s.crafted[a.id],a.crafts),goal:a.crafts}:{name:`Capture ${2+Math.floor(a.id/3)} native species`,current:a.names.filter((_,j)=>s.caught[a.id*10+j]).length,goal:2+Math.floor(a.id/3),done:a.names.filter((_,j)=>s.caught[a.id*10+j]).length>=2+Math.floor(a.id/3)},{name:`Donate ${a.donation} ${ITEMS['herb'+a.id].name}`,done:!!s.donated[a.id],current:s.donated[a.id]?a.donation:0,goal:a.donation,donation:true}];}
export function donate(s,area){const a=AREAS[area];if(area>s.badges.length||s.donated[area]||quantity(s,'herb'+area)<a.donation)return false;add(s,'herb'+area,-a.donation);s.donated[area]=true;return true;}
export function beginActivity(s,skill,id){if(!SKILLS[skill])return false;if(SKILLS[skill].type==='gather'){if(!Number.isInteger(id)||id<0||id>=10||lv(s,skill)<id*10+1||id>s.badges.length)return false;s.activity={skill,tier:id,progress:0};}else{const r=RECIPES.find(r=>r.id===id&&r.skill===skill);if(!r||lv(s,skill)<r.level||r.tier>s.badges.length||!canCraft(s,r))return false;s.activity={skill,recipe:id,progress:0};}s.trainer=skill;return true;}
export function canCraft(s,r){return s.gold>=r.gold&&Object.entries(r.cost).every(([k,v])=>quantity(s,k)>=v)&&(ITEMS[r.id].type!=='equipment'||s.gear.length<500);}
export function craft(s,r){if(!canCraft(s,r))return false;for(const[k,v]of Object.entries(r.cost))add(s,k,-v);s.gold-=r.gold;let q=0;if(ITEMS[r.id].type==='equipment'){const w=qualityWeights(lv(s,r.skill));q=choose(s,w.map((weight,i)=>({weight,i}))).i;s.gear.push({id:`g${++s.serial}`,item:r.id,quality:q});if(q>=4)log(s,`${['','','','','Epic','Legendary'][q]} craft: ${ITEMS[r.id].name}!`,true);}else add(s,r.id);s.skills[r.skill]+=r.xp;s.crafted[r.tier]++;s.totals.crafts++;return true;}
export function salvage(s,id){const index=s.gear.findIndex(g=>g.id===id);if(index<0||s.ferals.some(f=>Object.values(f.gear).includes(id)))return false;const g=s.gear[index];s.gear.splice(index,1);add(s,'scrap',1+Math.floor(g.quality/2));if(g.quality>=3)add(s,'dust',g.quality-2);return true;}
export function equip(s,feral,gear){const f=s.ferals.find(f=>f.id===feral),g=s.gear.find(g=>g.id===gear);if(!f||!g||s.combat||feralLevel(s,f)<ITEMS[g.item].level)return false;const slot=ITEMS[g.item].slot;for(const other of s.ferals)if(other.gear[slot]===gear){delete other.gear[slot];other.hp=Math.min(other.hp,stats(s,other).hp);}f.gear[slot]=gear;f.hp=Math.min(f.hp,stats(s,f).hp);return true;}
export function useItem(s,id,feral){const item=ITEMS[id];if(!item||quantity(s,id)<1)return false;const f=s.ferals.find(f=>f.id===feral);if(item.type==='lure'){if(s.trainer!=='combat'||s.boost?.until>s.clock)return false;s.boost={element:item.element,until:s.clock+30*60*1000};}
 else if(!f)return false;else if(item.type==='appraise'){if(f.appraised)return false;f.appraised=true;}else if(item.type==='revive'){if(f.hp>0||s.combat)return false;f.hp=Math.max(1,Math.round(stats(s,f).hp*item.heal));f.status={};}else if(item.type==='treat'){if(f.morale>=100)return false;f.morale=Math.min(100,f.morale+item.morale*(1+Math.min(1,f.bond/10000)*.15));f.bond=Math.min(10000,f.bond+3);}else if(item.type==='food'){if(f.hp<=0||f.hp>=stats(s,f).hp||(s.combat&&s.trainer!=='combat'))return false;f.hp=Math.min(stats(s,f).hp,f.hp+item.heal);}else return false;add(s,id,-1);return true;}
export function addToTeam(s,id){if(s.combat)return false;const f=s.ferals.find(f=>f.id===id);if(!f)return false;if(s.team.includes(id)){if(s.team.length===1)return false;s.team=s.team.filter(x=>x!==id);}else{if(s.team.length>=3)return false;s.team.push(id);}return true;}
function has(s,f,property){return Object.values(f.gear||{}).some(id=>{const g=s.gear.find(g=>g.id===id);return g&&ITEMS[g.item].property===property;});}
function recordEncounter(s,e){s.seen[e.species]=(s.seen[e.species]||0)+1;const sp=SPECIES[e.species];if(e.titan||e.element||sp.rarity==='Apex')log(s,`Encountered ${e.element?e.element+' ':''}${e.titan?'Titanblood ':''}${sp.name}${s.trainer!=='combat'?' while trainer was away':''}.`,true);}
export function startCombat(s,kind='wild',raid=0){if(s.combat||!ownedTeam(s).some(f=>f.hp>0))return false;if(kind==='champion'&&(s.badges.includes(s.area)||!tasks(s,AREAS[s.area]).every(t=>t.done)))return false;if(kind==='raid'){const r=RAIDS[raid];if(!r||s.badges.length<r.badge||quantity(s,r.key)<1||s.trainer!=='combat')return false;add(s,r.key,-1);}s.hold=false;s.combat={kind,raid,stage:0,enemies:[],respawn:0,kills:0,awaiting:false,mechanic:12,cast:0,focus:null};const waiting=s.wildEncounters?.[s.area];if(kind==='wild'&&waiting?.some(e=>e.hp>0)){s.combat.enemies=waiting;delete s.wildEncounters[s.area];}else spawnWave(s);return true;}
export function stopCombat(s){if(s.combat?.kind==='wild'&&s.combat.enemies.some(e=>e.hp>0)){s.wildEncounters??={};s.wildEncounters[s.area]=clone(s.combat.enemies);}if(s.combat?.kind==='raid')log(s,'Retreated from the raid. The entry key was consumed.');s.combat=null;s.hold=false;for(const f of ownedTeam(s)){f.status={};f.timer=0;f.cooldown=2;}}
function spawnWave(s){const c=s.combat,a=AREAS[s.area];let ids=[];if(c.kind==='wild'){const native=SPECIES.filter(sp=>sp.area===s.area);ids=Array.from({length:s.area<3?1:s.area<7?2:3},()=>choose(s,native).id);}else if(c.kind==='champion')ids=[a.id*10+9,a.id*10+1,...(a.id>=4?[a.id*10+8]:[])];else ids=c.stage===0?[RAIDS[c.raid].species-8,RAIDS[c.raid].species-3]:c.stage===1?[RAIDS[c.raid].species-1,RAIDS[c.raid].species-2]:[RAIDS[c.raid].species];
 c.enemies=ids.map((id,i)=>{const level=c.kind==='wild'?Math.max(1,a.level+Math.floor(rng(s)*4)):c.kind==='champion'?(a.id+1)*10:90+c.raid*5;const e=createFeral(s,id,level,c.kind==='wild');e.enemy=true;e.level=level;if(c.kind!=='wild'){e.iv=[55,55,55,55];e.titan=false;e.element=null;e.bossScale=c.kind==='raid'?8+c.stage*4:i===0?2.5:1.3;e.bossAttack=c.kind==='raid'?1.35:1.1;e.hp=stats(s,e).hp;}else recordEncounter(s,e);return e;});c.focus=null;c.respawn=0;c.mechanic=12;c.cast=0;for(const f of ownedTeam(s)){f.threat=0;f.timer=0;}}
export function captureChance(s,e,snare=s.snare){if(!e||e.hp<=0||!ITEMS[snare])return 0;const hp=e.hp/stats(s,e).hp;return Math.min(.9,Math.max(.015,(.15+(1-hp)*.6)*ITEMS[snare].strength/SPECIES[e.species].difficulty*(e.status.slow||e.status.poison?1.15:1)*(e.titan?.8:1)));}
export function capture(s,enemyId,auto=false){const c=s.combat,e=c?.enemies.find(e=>e.id===enemyId);if(!c||c.kind!=='wild'||s.trainer!=='combat'||!e||e.hp<=0||s.captureTimer>0||quantity(s,s.snare)<1||s.ferals.length>=s.storage)return false;if(auto){if(s.badges.length<6||quantity(s,'autoseal')<1)return false;add(s,'autoseal',-1);}s.captureTimer=B.captureCooldown;add(s,s.snare,-1);if(rng(s)<captureChance(s,e)*(auto?.8:1)){const f=clone(e);f.enemy=false;f.xp=0;f.level=1;f.appraised=false;f.status={};f.timer=0;f.cooldown=2;f.hp=stats(s,f).hp;s.ferals.push(f);s.caught[f.species]=(s.caught[f.species]||0)+1;s.totals.captures++;if([3,10,25].includes(s.caught[f.species])){s.gold+=s.caught[f.species]*50;add(s,'lens');log(s,`${SPECIES[f.species].name} research milestone: ${s.caught[f.species]} captures. Awarded gold and an appraisal lens.`);}e.hp=0;e.captured=true;log(s,`Captured ${e.element?e.element+' ':''}${e.titan?'Titanblood ':''}${SPECIES[e.species].name}!`,true);return 'caught';}log(s,`${SPECIES[e.species].name} broke free of the snare.`);return 'escaped';}
function fx(events,kind,target,value,extra={}){if(events)events.push({kind,target:target.id,value,...extra});}
function heal(s,actor,target,n,events){if(!target||target.hp<=0)return;const amount=Math.min(stats(s,target).hp-target.hp,Math.round(n*(SPECIES[actor.species].passive==='flow'?1.2:1)));if(amount>0){target.hp+=amount;actor.threat+=amount*.5;fx(events,'heal',target,amount);}}
function targetFor(s,actor,opponents){const living=opponents.filter(f=>f.hp>0);if(!living.length)return null;const taunt=living.find(f=>f.status.taunt>0);if(taunt)return taunt;if(!actor.enemy&&s.combat.focus){const focused=living.find(f=>f.id===s.combat.focus);if(focused)return focused;}if(actor.enemy&&s.combat.kind==='raid'&&s.combat.stage===1)return living.reduce((a,b)=>stats(s,a).def<stats(s,b).def?a:b);return living.reduce((a,b)=>a.threat>=b.threat?a:b);}
function strike(s,actor,target,mult,events,element=true){if(!target||target.hp<=0)return 0;const sp=SPECIES[actor.species],tp=SPECIES[target.species];if(tp.passive==='evasive'&&rng(s)<.08){fx(events,'miss',target,'DODGE');return 0;}const a=stats(s,actor),t=stats(s,target);const adv={Melee:'Ranged',Ranged:'Magic',Magic:'Melee'};const triangle=adv[sp.style]===tp.style?1.18:adv[tp.style]===sp.style?.85:1;const critical=rng(s)<(.05+(sp.passive==='keen'?.08:0)+(has(s,actor,'crit')?.04:0));const armor=t.def*(sp.passive==='pierce'?.85:1);let n=a.atk*mult*triangle*(.9+rng(s)*.2)*(critical?1.5:1)*50/(50+armor);if(tp.passive==='shell')n*=.9;if(tp.passive==='resolve'&&target.hp/t.hp<.35)n*=.8;if(sp.passive==='hunt'&&target.hp/t.hp<.5)n*=1.12;if(target.status.ward>0)n*=.65;if(has(s,target,'guard'))n*=.95;n=Math.max(1,Math.round(n));target.hp=Math.max(0,target.hp-n);actor.threat+=n*(sp.passive==='sturdy'?1.6:1)*(has(s,actor,'threat')?1.2:1);fx(events,critical?'crit':'damage',target,n,{source:actor.id});if(element&&actor.element&&rng(s)<.3){const el=actor.element;if(el==='Fire'){target.status.burn=6;target.burnPower=Math.max(1,a.atk*.03);}if(el==='Ice')target.status.slow=5;if(el==='Poison'){target.status.poison=4;target.poisonPower=Math.max(1,Math.min(t.hp*.02,a.atk*.3));}fx(events,'status',target,el);}
 if(target.hp===0)fx(events,'down',target,'DOWN');return n;}
function ability(s,f,allies,foes,events){const sp=SPECIES[f.species],id=sp.ability;let target=targetFor(s,f,foes);if(!target)return;const living=allies.filter(a=>a.hp>0);fx(events,'ability',f,ABILITIES[id].name);if(id==='taunt'){f.status.taunt=5;f.status.ward=5;f.threat+=50;}if(id==='haste')f.status.haste=7;if(id==='mend'){const weak=living.reduce((a,b)=>a.hp/stats(s,a).hp<b.hp/stats(s,b).hp?a:b);heal(s,f,weak,stats(s,f).atk*1.8,events);}if(id==='ward')for(const a of living){heal(s,f,a,stats(s,f).atk*.8,events);a.status.ward=5;}if(id==='pounce'){target=foes.filter(a=>a.hp>0).reduce((a,b)=>a.hp<b.hp?a:b);strike(s,f,target,1.7,events);}if(id==='volley'||id==='quake')for(const t of foes.filter(a=>a.hp>0)){strike(s,f,t,id==='volley'?.75:1.1,events);if(id==='quake')t.status.slow=5;}if(id==='rupture'){strike(s,f,target,1.3,events);target.status.sunder=7;}if(id==='execute')strike(s,f,target,target.hp/stats(s,target).hp<.35?2.2:1.4,events);if(id==='drain')heal(s,f,f,strike(s,f,target,1.4,events)*.5,events);if(has(s,f,'wardheal')&&['mend','ward','drain'].includes(id))for(const a of living)a.status.ward=5;}
function killReward(s,e){const sp=SPECIES[e.species],t=sp.area;add(s,sp.drop,1+(rng(s)<.2?1:0));add(s,['log','ore','fish','herb'][sp.special]+t,1);s.gold+=3+t*3;for(const f of ownedTeam(s).filter(f=>f.hp>0)){if(feralLevel(s,f)<cap(s))f.xp+=12+t*12;f.bond=Math.min(10000,f.bond+(s.trainer==='combat'?1:.25));}s.totals.kills++;if(rng(s)<B.raidKeyChance){const r=RAIDS[Math.min(2,Math.floor(t/4))];add(s,r.key);log(s,`RARE DROP · ${ITEMS[r.key].name}`,true);}if(rng(s)<.025)add(s,'fragment');if(e.titan||e.element||sp.rarity==='Apex')log(s,`Defeated ${e.element?e.element+' ':''}${e.titan?'Titanblood ':''}${sp.name}.`,true);}
function waveEnd(s,events){const c=s.combat;if(c.kind==='wild'){s.kills[s.area]++;c.kills++;c.respawn=2;return;}if(c.kind==='champion'){if(!s.badges.includes(s.area)){s.badges.push(s.area);s.gold+=500*(s.area+1);log(s,`${AREAS[s.area].champion} defeated! Earned ${AREAS[s.area].badge}. Feral cap: ${cap(s)}.`,true);}s.combat=null;fx(events,'victory',{id:'banner'},'BADGE EARNED');return;}if(c.stage<2){c.awaiting=true;log(s,`Raid stage cleared. Choose your next approach.`);}else{const r=RAIDS[c.raid];s.raidWins[c.raid]++;s.gold+=12000;add(s,'dust',12);add(s,'fragment',15);if(rng(s)<.035||s.raidWins[c.raid]%30===0){s.gear.push({id:`g${++s.serial}`,item:r.reward,quality:5});log(s,`RAID RELIC · ${ITEMS[r.reward].name}!`,true);}else log(s,`${r.boss} defeated. Relic guarantee: ${s.raidWins[c.raid]%30}/30.`,true);s.combat=null;}}
export function raidChoice(s,choice){const c=s.combat;if(!c||c.kind!=='raid'||!c.awaiting||!['restore','ward','haste'].includes(choice))return false;if(choice==='restore'){if(s.gold<500)return false;s.gold-=500;for(const f of ownedTeam(s).filter(f=>f.hp>0))f.hp=Math.min(stats(s,f).hp,f.hp+stats(s,f).hp*.4);}else for(const f of ownedTeam(s))f.status[choice]=12;c.stage++;c.awaiting=false;spawnWave(s);return true;}
export function command(s,kind){if(!s.combat||s.trainer!=='combat'||s.commandTimer>0)return false;if(kind==='guard')for(const f of ownedTeam(s))f.status.ward=5;else if(kind==='interrupt'){if(!s.combat.cast)return false;s.combat.cast=0;s.combat.mechanic=14;log(s,'The raid attack was interrupted.');}else return false;s.commandTimer=24;return true;}
export function step(s,dt,events=null,offline=false){if(!s.started)return;s.clock+=dt*1000;s.captureTimer=Math.max(0,s.captureTimer-dt);s.commandTimer=Math.max(0,s.commandTimer-dt);
 if(s.activity&&s.trainer!=='combat'){const a=s.activity,r=a.recipe?RECIPES.find(r=>r.id===a.recipe):null;if(r&&!canCraft(s,r)){log(s,`${ITEMS[r.id].name}: production stopped; materials, gold, or equipment space needed.`);s.activity=null;s.trainer='rest';}else{a.progress+=dt;const duration=r?r.seconds:5+a.tier*.6;if(a.progress>=duration){a.progress-=duration;if(r)craft(s,r);else{const kind={logging:'log',mining:'ore',fishing:'fish',foraging:'herb'}[a.skill];const n=1+(rng(s)<lv(s,a.skill)*.002?1:0);add(s,kind+a.tier,n);if(a.skill==='foraging'&&rng(s)<.6)add(s,'fiber');s.skills[a.skill]+=12+a.tier*10;s.totals.gathered+=n;}}}}
 const c=s.combat;if(!c||c.awaiting||(offline&&c.kind==='raid'))return;
 const allies=ownedTeam(s);if(!allies.some(f=>f.hp>0)){log(s,'Your team is incapacitated. Craft restorative medicine to return to battle.');s.combat=null;return;}
 if(c.respawn>0){c.respawn-=dt;if(c.respawn<=0)spawnWave(s);return;}
 for(const f of [...allies,...c.enemies]){if(f.hp<=0)continue;if(!f.enemy)f.morale=Math.max(0,f.morale-dt*B.moralePerSecond*(SPECIES[f.species].passive==='comfort'?.75:1)*(has(s,f,'care')?.85:1)*(1-Math.min(1,f.bond/10000)*.1));for(const k of Object.keys(f.status)){if(['burn','poison'].includes(k)&&f.status[k]>0){f[k+'Timer']=(f[k+'Timer']||0)+dt;if(f[k+'Timer']>=1){f[k+'Timer']-=1;const n=Math.max(1,Math.round(f[k+'Power']||1));f.hp=Math.max(0,f.hp-n);fx(events,'dot',f,n);}}f.status[k]=Math.max(0,f.status[k]-dt);}if(f.hp<=0)continue;
 if(!f.enemy&&s.trainer==='combat'&&s.autoEat&&f.hp/stats(s,f).hp<.45){const food=ITEMS[s.food];if(food?.type==='food'&&quantity(s,s.food)>0){const before=f.hp;useItem(s,s.food,f.id);fx(events,'heal',f,Math.round(f.hp-before));}}
 f.cooldown=Math.max(0,f.cooldown-dt);f.timer+=dt;const foes=f.enemy?allies:c.enemies,friends=f.enemy?c.enemies:allies;if(!f.enemy&&s.hold)continue;
 if(f.cooldown<=0){ability(s,f,friends,foes,events);f.cooldown=ABILITIES[SPECIES[f.species].ability].cooldown;}
 if(f.timer>=stats(s,f).interval){f.timer=0;const target=targetFor(s,f,foes),damage=strike(s,f,target,1,events);f.hits++;if(SPECIES[f.species].passive==='leech')heal(s,f,f,damage*.08,events);if(has(s,f,'regen'))heal(s,f,f,stats(s,f).hp*.01,events);if((f.element==='Lightning'&&f.hits%5===0)||(has(s,f,'chain')&&f.hits%4===0)){const next=foes.find(t=>t.hp>0&&t.id!==target?.id);if(next)strike(s,f,next,.65,events,false);}}
 }
 for(const e of c.enemies)if(e.hp<=0&&!e.rewarded){e.rewarded=true;if(c.kind==='wild'&&!e.captured)killReward(s,e);}
 if(c.kind==='raid'){if(c.cast>0){c.cast-=dt;if(c.cast<=0){for(const f of allies.filter(f=>f.hp>0)){const damage=Math.round(stats(s,f).hp*(f.status.ward>0?.18:.55));f.hp=Math.max(0,f.hp-damage);fx(events,'crit',f,damage);}c.mechanic=14;}}else{c.mechanic-=dt;if(c.mechanic<=0){c.cast=4;fx(events,'warning',{id:'banner'},'DEVASTATING ATTACK · 4s');}}}
 if(s.autoCapture&&s.trainer==='combat'&&c.kind==='wild'&&s.badges.length>=6){const rarity=['Common','Uncommon','Rare','Apex'];const e=c.enemies.find(e=>e.hp>0&&e.hp/stats(s,e).hp<.35&&(e.titan||e.element||rarity.indexOf(SPECIES[e.species].rarity)>=rarity.indexOf(s.autoRarity)));if(e)capture(s,e.id,true);}
 if(!allies.some(f=>f.hp>0)){log(s,'Your team was incapacitated. Your Ferals and equipment are safe.');s.combat=null;return;}
 if(c.enemies.every(e=>e.hp<=0)&&!c.respawn)waveEnd(s,events);
}
export function advance(s,seconds,offline=false){const allowed=Math.min(Math.max(0,seconds),B.offlineHours*3600);const before={gold:s.gold,kills:s.totals.kills,captures:s.totals.captures,gathered:s.totals.gathered,crafts:s.totals.crafts};for(let t=0;t<allowed;t+=B.step)step(s,Math.min(B.step,allowed-t),null,offline);return {seconds:allowed,gold:s.gold-before.gold,kills:s.totals.kills-before.kills,captures:s.totals.captures-before.captures,gathered:s.totals.gathered-before.gathered,crafts:s.totals.crafts-before.crafts};}
export function researchClaim(s,n){const count=Object.keys(s.caught).length;if(count<n||s.research.includes(n))return false;s.research.push(n);s.gold+=n*100;add(s,'lens',Math.max(1,n/10));s.storage+=5;return true;}
export function upgradeStorage(s){const cost=Math.floor(500*1.65**((s.storage-30)/10));if(s.gold<cost||s.storage>=300)return false;s.gold-=cost;s.storage+=10;return true;}
export function release(s,id){const index=s.ferals.findIndex(f=>f.id===id);if(index<0||s.team.includes(id)||Object.values(s.ferals[index].gear).length)return false;s.ferals.splice(index,1);return true;}
export function validate(s){if(!s||s.schema!==B.schema||!Array.isArray(s.ferals)||!Array.isArray(s.gear)||!s.bag||!s.skills||!Array.isArray(s.badges))throw Error('Unsupported or damaged save. Original file has not been changed.');const finiteTree=(v)=>{if(typeof v==='number'&&(!Number.isFinite(v)||Math.abs(v)>1e15))throw Error('Invalid save number');if(v&&typeof v==='object')for(const x of Object.values(v))finiteTree(x);};finiteTree(s);if(s.gold<0||s.ferals.length>300||s.gear.length>1000||s.team.length>3||new Set(s.ferals.map(f=>f.id)).size!==s.ferals.length||new Set(s.gear.map(g=>g.id)).size!==s.gear.length)throw Error('Invalid save inventory');for(const [id,n]of Object.entries(s.bag))if(!ITEMS[id]||!Number.isSafeInteger(n)||n<0)throw Error('Invalid resource');for(const f of s.ferals)if(!SPECIES[f.species]||f.iv.length!==4||f.iv.some(x=>!Number.isInteger(x)||x<1||x>100)||f.hp<0||f.morale<0||f.morale>100||f.xp<0||!f.gear||!f.status)throw Error('Invalid Feral');for(const g of s.gear)if(ITEMS[g.item]?.type!=='equipment'||!Number.isInteger(g.quality)||g.quality<0||g.quality>5)throw Error('Invalid equipment');if(s.team.some(id=>!s.ferals.some(f=>f.id===id))||s.badges.some((x,i)=>x!==i)||s.badges.length>10)throw Error('Invalid progression');for(const k of Object.keys(SKILLS))if(!Number.isFinite(s.skills[k])||s.skills[k]<0)throw Error('Invalid skill');return s;}
