import {firebaseConfig} from './firebase-config.mjs';
import {clone,validate,quantity,add} from './engine.mjs';
import {ITEMS} from './data.mjs';
let sdk,auth,db,revision=null,user=null,readyPromise;
export const online={user:null,connected:false,status:'Local save',revision:null};
export async function connect(){if(readyPromise)return readyPromise;readyPromise=(async()=>{const base='https://www.gstatic.com/firebasejs/12.18.0/';const [app,a,f]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-auth.js'),import(base+'firebase-firestore.js')]);sdk={...a,...f};const instance=app.initializeApp(firebaseConfig);auth=a.getAuth(instance);db=f.getFirestore(instance);await auth.authStateReady();user=auth.currentUser;online.user=user?{uid:user.uid,email:user.email}:null;return online;})().catch(e=>{readyPromise=null;throw e;});return readyPromise;}
export async function login(email,password,register=false){await connect();const result=await (register?sdk.createUserWithEmailAndPassword:sdk.signInWithEmailAndPassword)(auth,email,password);user=result.user;online.user={uid:user.uid,email:user.email};revision=null;online.connected=false;return await readCloud();}
export async function resetPassword(email){await connect();await sdk.sendPasswordResetEmail(auth,email);}
export async function logout(){await connect();await sdk.signOut(auth);user=null;revision=null;online.user=null;online.connected=false;online.status='Local save';}
export async function readCloud(){await connect();if(!user)throw Error('Sign in first.');const d=await sdk.getDoc(sdk.doc(db,'players',user.uid));const data=d.exists()?d.data():null;revision=data?.revision||0;online.revision=revision;online.connected=false;return data?{state:validate(JSON.parse(data.save)),revision}:null;}
export function acceptCloud(){online.connected=true;online.status='Cloud connected';}
function playerPayload(state,rev){validate(state);return {save:JSON.stringify(state),revision:rev,name:state.name,updatedAt:sdk.serverTimestamp()};}
export async function pushCloud(state){if(!online.connected||!user)throw Error('Connect your cloud save first.');const expected=revision,ref=sdk.doc(db,'players',user.uid);const snapshot=clone(state);await sdk.runTransaction(db,async tx=>{const doc=await tx.get(ref),current=doc.exists()?doc.data().revision:0;if(current!==expected)throw Error('Another device changed this save. Export your local save, then reconnect to choose which progress to keep.');tx.set(ref,playerPayload(snapshot,current+1));});revision=expected+1;online.revision=revision;online.status='Cloud saved';}
export async function publishScore(state){if(!online.connected)return;const total=Object.values(state.skills).reduce((a,v)=>a+v,0);await sdk.setDoc(sdk.doc(db,'scores',user.uid),{name:state.name,champions:state.badges.length,collection:Object.keys(state.caught).length,skillXP:total,raids:state.raidWins.reduce((a,v)=>a+v,0),updatedAt:sdk.serverTimestamp()});}
export async function scores(){await connect();if(!user)throw Error('Sign in to view your group.');return (await sdk.getDocs(sdk.query(sdk.collection(db,'scores'),sdk.orderBy('skillXP','desc'),sdk.limit(50)))).docs.map(d=>({id:d.id,...d.data()}));}
export async function listings(){await connect();if(!user)throw Error('Sign in to trade.');return (await sdk.getDocs(sdk.query(sdk.collection(db,'market'),sdk.where('status','==','open'),sdk.limit(80)))).docs.map(d=>({id:d.id,...d.data()}));}
export async function marketAction(state,action,params){if(!online.connected||!user)throw Error('Connect your cloud save before trading.');const expected=revision,pr=sdk.doc(db,'players',user.uid);let next=clone(state);let marketRef;
 if(action==='list'){const {item,count,price}=params;if(!ITEMS[item]||!['material','food','treat','revive','snare','appraise','lure','automation'].includes(ITEMS[item].type)||!Number.isSafeInteger(count)||count<1||count>100000||!Number.isSafeInteger(price)||price<1||price>100000000||quantity(next,item)<count)throw Error('Check the item, quantity, and total price.');if(next.gold<Math.max(1,Math.ceil(price*.02)))throw Error('Not enough gold for the 2% listing fee.');marketRef=sdk.doc(sdk.collection(db,'market'));add(next,item,-count);next.gold-=Math.max(1,Math.ceil(price*.02));}
 else if(action!=='claim')marketRef=sdk.doc(db,'market',params.id);
 const prepared=clone(next);await sdk.runTransaction(db,async tx=>{next=clone(prepared);const player=await tx.get(pr);if(!player.exists()||player.data().revision!==expected)throw Error('Cloud save changed. Reconnect before trading.');
 if(action==='list')tx.set(marketRef,{seller:user.uid,sellerName:next.name,item:params.item,count:params.count,price:params.price,status:'open',createdAt:sdk.serverTimestamp()});
 else if(action==='claim'){const cr=sdk.doc(db,'credits',user.uid),credit=await tx.get(cr);if(!credit.exists()||credit.data().gold<=0)throw Error('No sale proceeds to collect.');next.gold+=credit.data().gold;tx.set(cr,{gold:0});}
 else {const doc=await tx.get(marketRef);if(!doc.exists()||doc.data().status!=='open')throw Error('This listing is no longer available.');const listing=doc.data();if(action==='cancel'){if(listing.seller!==user.uid)throw Error('This is not your listing.');add(next,listing.item,listing.count);tx.update(marketRef,{status:'cancelled'});}else if(action==='buy'){if(listing.seller===user.uid)throw Error('You cannot buy your own listing.');if(next.gold<listing.price)throw Error('Not enough gold.');const cr=sdk.doc(db,'credits',listing.seller),credit=await tx.get(cr);next.gold-=listing.price;add(next,listing.item,listing.count);tx.set(cr,{gold:(credit.exists()?credit.data().gold:0)+Math.floor(listing.price*.95),lastListing:marketRef.id});tx.update(marketRef,{status:'sold',buyer:user.uid});}else throw Error('Unknown market action');}
 tx.set(pr,playerPayload(next,expected+1));});revision=expected+1;online.revision=revision;return next;}
export function friendlyError(e){const code=e.code||'';if(code.includes('invalid-credential'))return 'Email or password is incorrect.';if(code.includes('email-already'))return 'That email already has an account. Use Sign in.';if(code.includes('weak-password'))return 'Choose a password with at least 6 characters.';if(code.includes('permission-denied'))return 'Firebase access is blocked. The project owner needs to publish firestore.rules in the Firebase Console.';if(code.includes('operation-not-allowed'))return 'Email/password sign-in needs to be enabled in Firebase Authentication.';if(code.includes('network')||e instanceof TypeError)return 'Cannot reach Firebase. Your local game is still saved. Check your connection and try again.';return e.message||'Connection failed. Your local save is safe.';}
