import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {newGame,startGame,clone,quantity} from './engine.mjs';
const records=new Map();let serial=0,retry=false;
const doc=(...args)=>args.length===1?args[0].path+'/listing'+(++serial):args.length===2?args[0].path+'/'+args[1]:args.slice(1).join('/');
const snapshot=path=>({exists:()=>records.has(path),data:()=>clone(records.get(path))});
const sdk={doc,collection:(_,path)=>({path}),getDoc:async ref=>snapshot(ref),serverTimestamp:()=>123,setDoc:async(ref,data)=>records.set(ref,clone(data)),runTransaction:async(_,fn)=>{const run=async()=>{const pending=[];await fn({get:async ref=>snapshot(ref),set:(ref,data)=>pending.push(()=>records.set(ref,clone(data))),update:(ref,data)=>pending.push(()=>records.set(ref,{...records.get(ref),...clone(data)}))});return pending;};if(retry){retry=false;await run();}const writes=await run();writes.forEach(write=>write());}};
async function client(uid){globalThis.__h={sdk,user:{uid,email:uid+'@example.test'}};let source=await fs.readFile(new URL('./online.mjs',import.meta.url),'utf8');source=source.replace("'./firebase-config.mjs'",JSON.stringify(new URL('./firebase-config.mjs',import.meta.url).href)).replace("'./engine.mjs'",JSON.stringify(new URL('./engine.mjs',import.meta.url).href)).replace("'./data.mjs'",JSON.stringify(new URL('./data.mjs',import.meta.url).href));source=source.replace('let sdk,auth,db,revision=null,user=null,readyPromise;',`let sdk=globalThis.__h.sdk,auth={},db={},revision=null,user=globalThis.__h.user,readyPromise=Promise.resolve(); // ${uid}`);return import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));}
function state(name){const s=newGame(1);startGame(s,0,name);s.gold=1000;s.bag.log0=20;return s;}
const seller=await client('seller'),buyer=await client('buyer'),secondBuyer=await client('second');let a=state('Seller'),b=state('Buyer'),c=state('Second');
for(const [client,s] of [[seller,a],[buyer,b],[secondBuyer,c]]){await client.readCloud();client.acceptCloud();await client.pushCloud(s);}
retry=true;a=await seller.marketAction(a,'list',{item:'log0',count:5,price:100});const listing=[...records.keys()].find(k=>k.startsWith('market/')),id=listing.split('/')[1];assert.equal(a.bag.log0,15);assert.equal(a.gold,998);console.log('PASS listing escrow and 2% fee');
retry=true;b=await buyer.marketAction(b,'buy',{id});assert.equal(b.gold,900);assert.equal(b.bag.log0,25);assert.equal(records.get('credits/seller').gold,95);assert.equal(records.get(listing).status,'sold');console.log('PASS purchase is retry-safe and pays 95% to seller');
await assert.rejects(secondBuyer.marketAction(c,'buy',{id}),/no longer available/);assert.equal(c.gold,1000);assert.equal(c.bag.log0,20);console.log('PASS a sold listing cannot be purchased again');
retry=true;a=await seller.marketAction(a,'claim',{});assert.equal(a.gold,1093);assert.equal(records.get('credits/seller').gold,0);await assert.rejects(seller.marketAction(a,'claim',{}),/No sale proceeds/);console.log('PASS sale proceeds can only be collected once');
a=await seller.marketAction(a,'list',{item:'log0',count:4,price:50});const open=[...records.entries()].find(([k,v])=>k.startsWith('market/')&&v.status==='open')[0];retry=true;a=await seller.marketAction(a,'cancel',{id:open.split('/')[1]});assert.equal(a.bag.log0,15);assert.equal(a.gold,1092);console.log('PASS cancel returns escrow once and keeps listing fee');
records.get('players/seller').revision++;await assert.rejects(seller.pushCloud(a),/Another device/);console.log('PASS stale cloud revisions cannot overwrite another device');
