import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const listeners={},display={matches:false};
globalThis.window={matchMedia:()=>display,addEventListener:(name,fn)=>listeners[name]=fn};
Object.defineProperty(globalThis,'navigator',{value:{userAgent:'iPhone',platform:'iPhone',maxTouchPoints:1},configurable:true});
const app=await import('./install.mjs');
assert.match(app.installPanel(),/Install Feralwild/);
assert.match((await app.installGame()).body,/Safari/);
navigator.userAgent='Android';navigator.platform='Linux';
assert.match((await app.installGame()).body,/Install app/);
let prompted=0,prevented=0;
listeners.beforeinstallprompt({preventDefault(){prevented++;},async prompt(){prompted++;},userChoice:Promise.resolve({outcome:'dismissed'})});
assert.match((await app.installGame()).title,/whenever/);
await app.installGame();assert.equal(prompted,1);assert.equal(prevented,1);
listeners.beforeinstallprompt({preventDefault(){},async prompt(){throw Error('expired');}});
assert.match((await app.installGame()).body,/Install app/);
listeners.appinstalled();assert.doesNotMatch(app.installPanel(),/data-action/);
display.matches=true;assert.match(app.installPanel(),/playing in the installed app/);
console.log('PASS install instructions, prompt lifecycle, dismissal, fallback, and installed state');
const m=JSON.parse(fs.readFileSync('manifest.webmanifest'));
assert.equal(m.display,'standalone');assert.equal(m.scope,'./');assert.equal(m.start_url,'./');assert.equal(m.id,'./');
const html=fs.readFileSync('index.html','utf8');assert.equal((html.match(/rel="manifest"/g)||[]).length,1);assert.match(html,/apple-touch-icon.png/);
for(const icon of m.icons){const png=fs.readFileSync(icon.src);const size=Number(icon.sizes.split('x')[0]);assert.equal(png.readUInt32BE(16),size);assert.equal(png.readUInt32BE(20),size);}
let cached=[];const worker={};
vm.runInNewContext(fs.readFileSync('service-worker.js','utf8'),{self:{addEventListener:(n,fn)=>worker[n]=fn},caches:{open:async()=>({addAll:async files=>{cached=files;}})}});
let task;worker.install({waitUntil:p=>task=p});await task;
for(const file of cached)assert(fs.existsSync(file),'Missing cached file: '+file);
for(const file of ['install.mjs','manifest.webmanifest','icon-192.png','icon-512.png','apple-touch-icon.png'])assert(cached.includes(file));
console.log('PASS manifest, GitHub subpath scope, PNG dimensions, and complete offline install assets');
